## 异常处理
python异常处理。   
### python异常标准
BaseException，所有异常的基类；  
SystemExit，解释器请求退出；    
KeyboardInterrupt，用户中断执行(通常是输入^C)；    
Exception，常规错误的基类；    
StopIteration，迭代器没有更多的值；    
GeneratorExit，生成器(generator)发生异常来通知退出；    
StandardError，所有的内建标准异常的基类；    
ArithmeticError，所有数值计算错误的基类；    
FloatingPointError，浮点计算错误；    
OverflowError，数值运算超出最大限制；    
ZeroDivisionError，除(或取模)零 (所有数据类型)；    
AssertionError，断言语句失败；    
AttributeError，对象没有这个属性；    
EOFError，没有内建输入,到达EOF 标记；    
EnvironmentError，操作系统错误的基类；    
IOError，输入/输出操作失败；    
OSError，操作系统错误；    
WindowsError，系统调用失败；    
ImportError，导入模块/对象失败；    
LookupError，无效数据查询的基类；   
IndexError，序列中没有此索引(index)；   
KeyError，映射中没有这个键；   
MemoryError，内存溢出错误(对于Python 解释器不是致命的)；   
NameError，未声明/初始化对象 (没有属性)；   
UnboundLocalError，访问未初始化的本地变量；   
ReferenceError，弱引用(Weak reference)试图访问已经垃圾回收了的对象；   
RuntimeError，一般的运行时错误；   
NotImplementedError，尚未实现的方法；   
SyntaxError，Python 语法错误；   
IndentationError，缩进错误；   
TabError，Tab 和空格混用；   
SystemError，一般的解释器系统错误；   
TypeError，对类型无效的操作；   
ValueError，传入无效的参数；   
UnicodeError，Unicode 相关的错误；   
UnicodeDecodeError，Unicode 解码时的错误；   
UnicodeEncodeError，Unicode 编码时错误；   
UnicodeTranslateError，Unicode 转换时错误；   
Warning，警告的基类；   
DeprecationWarning，关于被弃用的特征的警告；   
FutureWarning，关于构造将来语义会有改变的警告；   
OverflowWarning，旧的关于自动提升为长整型(long)的警告；   
PendingDeprecationWarning，关于特性将会被废弃的警告；  
RuntimeWarning，可疑的运行时行为(runtime behavior)的警告；    
SyntaxWarning，可疑的语法的警告；  
UserWarning，用户代码生成的警告；   
### 什么是异常  
异常是一个时间，在程序执行过程中发生，影响了程序的正常执行。   
通常，python如果正常处理程序时就会发生一个异常。   
我们需要在python发生异常的时候捕获他，否则长须会终止执行。   
### try/except/else
通常处理异常会使用try/except/else语句  
#### 捕捉单个异常
比如index越界的问题，通常如果越界了，编译器会报错。   
但是如果我们引入异常处理。  
```Python
try:
    list1 = [1, 2]
    print(list1[2])
except IndexError:
    print("Error,超出index范围")
else:
    print("no error")
```  
则以上代码可以正常运行。   
except后加对应的异常名称，则可以捕获对应的异常。   
#### 捕捉全部异常
通常在使用except的时候，也可以选择什么异常名字都不加，这样将会捕获所有的异常。   
```Python
try:
    list1 = [1, 2]
    print(list1[2])
except:
    print("Error,超出index范围")
else:
    print("no error")
```  
**但是这么做，是不推荐的。**    
#### 捕捉多个异常  
如果有需要捕捉多个异常的情况下，那么可以使用多个except即可。   
```Python
try:
    list1 = [1, 2]
    print(list1[2])
except IndexError:
    print("Error,超出index范围")
except RuntimeError:
    print("Error,运行时错误")
else:
    print("no error")
```  
### try/finally  
try-finally 语句无论是否发生异常都将执行最后的代码。   
```Python
try:   
	# 语句   
finally:  
	# 退出try时总是会执行  
```  
fianlly块中的语句，在退出try时总是会执行的。   
### 手动触发异常 raise语句
我们可以通过raise语句来手动触发异常。   
```Python
try:
    list1 = [1, 2]
    if len(list1) < 3:
        raise Exception("Index is error")
    print(list1[2])
except IndexError:
    print("Error")
except Exception:
    print("触发自定义异常")
else:
    print("no error")
```
上述代码如果执行的话，就会跳转到“触发自定义异常”中去了，且不会执行  
```Python
print(list1[2])   
```  
的内容。  